blank_issues_enabled: false
contact_links:
  - name: Questions & Usage Discussions
    url: https://github.com/spectralDNS/jaxfun/discussions
    about: Ask questions, share ideas, and have open-ended discussions.
